language: rust

cache: cargo

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

rust: nightly

os:
  - linux

matrix:
  fast_finish: true

notifications:
  email: false

script: scripts/run.sh
